name: Deploy Data Factory Changes to QA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dev Repository
      uses: actions/checkout@v3

    - name: Clone QA Repository
      run: |
        # Clone into a separate directory outside the current repository
        git clone https://chirag504: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@github.com/chirag504/adf_qa.git ../adf_qa

    - name: Copy Folders from Dev to QA
      run: |
        cp -r dataset ../adf_qa/dataset
        cp -r linkedService ../adf_qa/linkedService
        cp -r pipeline ../adf_qa/pipeline

    - name: Update Connection String for QA
      working-directory: ../adf_qa
      run: |
        sed -i 's/"fileSystem": "adf-dev"/"fileSystem": "adf-qa"/g' dataset/blob_dump.json
        sed -i 's/"schema": "sample"/"schema": "qa_sample"/g' dataset/AzureSqlTable1.json
        sed -i 's/"server": "adf-dev-sql-server-283902.database.windows.net"/"server": "adf-qa-sql-server-7839.database.windows.net"/g' linkedService/sql_db.json
        sed -i 's/"database": "adf-dev-db-9902"/"database": "adf-qa-db-764899"/g' linkedService/sql_db.json

    - name: Commit and Push Changes to QA Repository
      working-directory: ../adf_qa
      run: |
        git config --global user.email "chirag@dreamitcs.com"
        git config --global user.name "chirag504"
        git add .
        git commit -m "Updated connection strings and paths for QA from Dev repo"
        git remote remove origin
        git remote add origin https://chirag504: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@github.com/chirag504/adf_qa.git
        git push --set-upstream origin main
